server:
  port: 8882

resend:
  apiKey: reXXX #apiKey resend
  from-email: XX@XX.dev #from-email resend
  to: XX@XX.com #static email because we don't have email in payMessage just same like phone

twilio:
  phone: +48XXXXXXXXX #Twilio Phone
  account-sid: XXX #Twilio account-sid
  auth-token: XXX #auth-token
  fromNumber: +12XXX #Twilio fromNumber

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservicesdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
